modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Team-Arcadia/Arcadia-LootBox/issues"

[[mods]]
modId="arcadialootbox"
version="${mod_version}"
displayName="Arcadia Lootbox"
authors="vyrriox"
description='''
A premium lootbox system with custom visuals, hub integration, and full configuration.
Powered by Arcadia Lib.
'''
logoFile="logo.png"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.arcadialootbox]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.arcadialootbox]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.arcadialootbox]]
modId="arcadia_lib"
type="required"
versionRange="[1.2.14,)"
ordering="AFTER"
side="BOTH"
