blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/xjF8Rtzyd4
    about: "Get help on our Discord server | Obtenir de l'aide sur Discord"
  - name: Arcadia Website
    url: https://arcadia-echoes-of-power.fr/
    about: "Visit our website | Visitez notre site"
